apiVersion: 1

datasources:
  # InfluxDB datasource for metrics
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb
    database: ""
    user: ""
    password: ""
    jsonData:
      version: Flux
      organization: tower_hooker
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: true

  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: false
    editable: true 